### PR TITLE
Added style and config files for pre-commit hook

### PR DESCRIPTION
**Pull request by vpoliukh**
Added style and config files for pre-commit hook.
How to use could be seen in [Jira task #AL-10019](https://anodot.atlassian.net/browse/AL-10019)

### CODE REVIEW

**Comment by AntonZelenin** [comment]
I would change the following values:
coalesce_brackets=True
dedent_closing_brackets=True
split_before_arithmetic_operator=True
split_penalty_after_opening_bracket=0 or something close to 0, mb 30, not sure

Also probably would be better to keep
```
supported = [
    source.TYPE_CLICKHOUSE,
    source.TYPE_DIRECTORY,
    source.TYPE_INFLUX,
    source.TYPE_KAFKA,
    source.TYPE_MYSQL,
    source.TYPE_ORACLE,
    source.TYPE_POSTGRES
]
```
instead of
```
supported = [
    source.TYPE_CLICKHOUSE, source.TYPE_DIRECTORY, source.TYPE_INFLUX, source.TYPE_KAFKA,
    source.TYPE_MYSQL, source.TYPE_ORACLE, source.TYPE_POSTGRES
]
```
but I don't know how to achieve it

@dariakharlan what do you think?

**Comment by vpoliukh** [comment]
This kind of reformat
```python
supported = [
    source.TYPE_CLICKHOUSE, source.TYPE_DIRECTORY, source.TYPE_INFLUX, source.TYPE_KAFKA,
    source.TYPE_MYSQL, source.TYPE_ORACLE, source.TYPE_POSTGRES
]
```
will happen only if initially list elements will be placed in one big single line bigger than 100 chars

**Comment by AntonZelenin** [comment]
No, initially every value was on a separate line, but after reformat there were two lines like I showed. At least with my configuration. You can find `def supports_schema(pipeline_: Pipeline):` and test there

**Review by dariakharlan — CHANGES_REQUESTED** [review]
Create a makefile command to automate the installation
Also, it would be nice to have a section in the readme file on how to set up dev environment, what commands to run (including this tool installation and rrdtool thing we had)

**Comment by dariakharlan** [comment]
Yes, I agree that each item on a separate line looks better

**Comment by vpoliukh** [comment]
Checked, current style saves each list item on single line if list elements end with comma, like this
```python
supported = [
    source.TYPE_CLICKHOUSE,
    source.TYPE_DIRECTORY,
    source.TYPE_INFLUX,
    source.TYPE_KAFKA,
    source.TYPE_MYSQL,
    source.TYPE_ORACLE,
    source.TYPE_POSTGRES,
]
```

Which also good, because if new element will be added to the list, then git diff will show only 1 changed line (that added element), instead of 2 lines (comma to pre-last and new added element)

**Review by AntonZelenin — APPROVED** [review]

**Review by dariakharlan — APPROVED** [review]

**Pull request merged**
